### PR TITLE
Changed the Title and added .gitignore file

### PR DESCRIPTION
**Pull request by nelsonle39**
Modified 'Hello World' to 'Hello Nelson Le' and added a .gitignore file for the obj and Properties directories

### CODE REVIEW

**Comment by nelsonle345** [comment]
Add middle name

**Review by nelsonle345 — DISMISSED** [review]
Add your middle name

**Comment by nelsonle39** [comment]
Midde name added!

**Review by nelsonle345 — APPROVED** [review]
Changes Approved

**Pull request merged**
